<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>exercises_R_Binomial_Quarto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="exercises_R_binomial_Poisson_files/libs/clipboard/clipboard.min.js"></script>
<script src="exercises_R_binomial_Poisson_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="exercises_R_binomial_Poisson_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="exercises_R_binomial_Poisson_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="exercises_R_binomial_Poisson_files/libs/quarto-html/popper.min.js"></script>
<script src="exercises_R_binomial_Poisson_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exercises_R_binomial_Poisson_files/libs/quarto-html/anchor.min.js"></script>
<link href="exercises_R_binomial_Poisson_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exercises_R_binomial_Poisson_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exercises_R_binomial_Poisson_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exercises_R_binomial_Poisson_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exercises_R_binomial_Poisson_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">exercises_R_Binomial_Quarto</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="series-3-applied-machine-learning-and-predictive-modelling-1-binomial-binary-glm-poisson" class="level1">
<h1>Series 3: Applied Machine Learning and Predictive Modelling 1 Binomial binary GLM Poisson</h1>
<p>Load the x-ray dataset (file “Xray.RDS”). This study refers to a “study carried out to investigate the connection between X-ray usage and acute myeloid leukemia in childhood” (for further information see the help page about the amlxray dataset in {faraway} package). We work on a subset of the original data, in particular, we consider the following variables:</p>
<p>• disease: is the response variable (1 = diseased, 0 = healthy)</p>
<p>• Sex: Sex of the patient</p>
<p>• age: Age of the child (in years)</p>
<p>• downs: Presence of the Down syndrome</p>
<p>• Mray: Did the mother ever had an Xray</p>
<p>• Fray: Did the father ever had an Xray</p>
<p>• CnRay.num: Total number of Xrays of the child “1” = none; “2” = 1 or 2; “3” = 3 or 4; “4” = 5 or more</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>d.xray <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"Xray.RDS"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(d.xray)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Classes 'tbl_df', 'tbl' and 'data.frame':   112 obs. of  7 variables:
 $ Sex      : Factor w/ 2 levels "F","M": 1 2 1 2 2 1 1 2 1 2 ...
 $ disease  : num  1 1 0 1 1 1 1 0 0 0 ...
 $ age      : int  0 6 8 1 4 9 17 5 0 7 ...
 $ downs    : Factor w/ 2 levels "no","yes": 1 1 1 2 1 1 1 1 1 1 ...
 $ Mray     : Factor w/ 2 levels "no","yes": 1 1 1 1 2 2 1 1 1 1 ...
 $ Fray     : Factor w/ 2 levels "no","yes": 1 1 1 1 1 1 1 1 1 1 ...
 $ CnRay.num: num  1 3 1 1 1 1 2 1 1 1 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d.xray)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sex disease age downs Mray Fray CnRay.num
1   F       1   0    no   no   no         1
2   M       1   6    no   no   no         3
3   F       0   8    no   no   no         1
4   M       1   1   yes   no   no         1
5   M       1   4    no  yes   no         1
6   F       1   9    no  yes   no         1</code></pre>
</div>
</div>
<p>Question</p>
<p>Visualise the data. You may want to take advantage of the pairs() function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(d.xray)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercises_R_binomial_Poisson_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(pairs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("GGally")</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an advanced pairs plot viusualisation, coloring by the disease status</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(d.xray, <span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">as.factor</span>(disease)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercises_R_binomial_Poisson_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Question</p>
<p>Fit a starting model to the data. Start by assuming linearity for the continuous predictors and assume that no interaction is needed. Comment on the results obtained wit the summary() function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>linearity<span class="ot">=</span><span class="fu">lm</span>(disease<span class="sc">~</span>CnRay.num<span class="sc">+</span>age,d.xray)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linearity)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = disease ~ CnRay.num + age, data = d.xray)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8570 -0.3680 -0.3072  0.5306  0.7044 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 0.154829   0.098989   1.564    0.121  
CnRay.num   0.140789   0.060097   2.343    0.021 *
age         0.011586   0.009073   1.277    0.204  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4807 on 109 degrees of freedom
Multiple R-squared:  0.08177,   Adjusted R-squared:  0.06493 
F-statistic: 4.854 on 2 and 109 DF,  p-value: 0.009566</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate is 0,154, that means if all other variables are 0, the chance of getting the disease is 0.154</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># CnRay.num coefficient is 0.14 that means, per time X RAY raises the chance of getting disease by 0.14. this is statistically significant.</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># age coefficient is 0.011, that means per year older the person is, it raises the chance of being sick by 0.011. however it is statistically not significant.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><img src="answer%20correction%201.png" class="img-fluid" alt="correction answer glm"> <img src="answer%20correction%202.png" class="img-fluid" alt="correction answer glm"></p>
<p>Question Interpret the coefficients of SexM and age</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>linearityglm<span class="ot">&lt;-</span><span class="fu">glm</span>(disease<span class="sc">~</span>CnRay.num<span class="sc">+</span>age<span class="sc">+</span>Sex,<span class="at">family=</span><span class="st">"binomial"</span>,d.xray)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(linearityglm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = disease ~ CnRay.num + age + Sex, family = "binomial", 
    data = d.xray)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.91241    0.52334  -3.654 0.000258 ***
CnRay.num    0.63570    0.30889   2.058 0.039588 *  
age          0.03960    0.04038   0.981 0.326754    
SexM         0.91444    0.41089   2.225 0.026048 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 152.97  on 111  degrees of freedom
Residual deviance: 138.55  on 108  degrees of freedom
AIC: 146.55

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="answer%20correction%203.png" class="img-fluid figure-img"></p>
<figcaption>correction answer glm</figcaption>
</figure>
</div>
<p><img src="interpretation%201.png" class="img-fluid" alt="correction answer glm"> <img src="interpretation%202.png" class="img-fluid" alt="correction answer glm"></p>
<p>Question Look at the estimated effect of the variable downs and its p-value. Do the results make sense to you? Comment.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># including the 'downs' variable</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model_with_downs <span class="ot">&lt;-</span> <span class="fu">glm</span>(disease <span class="sc">~</span> CnRay.num <span class="sc">+</span> age <span class="sc">+</span> Sex <span class="sc">+</span> downs, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">family =</span> <span class="st">"binomial"</span>, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> d.xray)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_with_downs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = disease ~ CnRay.num + age + Sex + downs, family = "binomial", 
    data = d.xray)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   -1.95535    0.52540  -3.722 0.000198 ***
CnRay.num      0.63767    0.30693   2.078 0.037751 *  
age            0.04541    0.04074   1.115 0.264952    
SexM           0.86486    0.41375   2.090 0.036593 *  
downsyes      15.97347 1455.39758   0.011 0.991243    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 152.97  on 111  degrees of freedom
Residual deviance: 136.76  on 107  degrees of freedom
AIC: 146.76

Number of Fisher Scoring iterations: 14</code></pre>
</div>
</div>
<section id="what-the-output-showsinterpretation" class="level2">
<h2 class="anchored" data-anchor-id="what-the-output-showsinterpretation">What the Output Shows（interpretation）</h2>
<p>The output for the downsyes variable is highly unusual:</p>
<p>Massive Coefficient (Estimate): The coefficient is extremely large (15.97). This suggests a massive increase in the odds of the disease.</p>
<p>Astronomical Standard Error (Std. Error): The standard error is huge (1455.40). This indicates the model is extremely uncertain about the exact size of the coefficient.</p>
<p>Non-Significant P-value (Pr(&gt;|z|)): The p-value is almost 1 (0.991), which means the effect is statistically not significant at all. It makes sense. almost all children with down has this disease.</p>
</section>
<section id="question" class="level2">
<h2 class="anchored" data-anchor-id="question">Question</h2>
<p><strong>Differences Between Binomial and Binary Data</strong> The primary difference is that binary data represents the outcome of a single event (or “trial”) that has only two possible outcomes (e.g., success/failure, yes/no, 1/0). In contrast, binomial data represents the total number of successes in a fixed number of independent binary trials.</p>
<p><strong>What Model Should You Fit to Binary Data?</strong> you should fit a logistic regression model. This is a type of Generalized Linear Model (GLM) that is specifically designed for binary outcomes. In R, this is done using the glm() function with the argument family = “binomial”.</p>
<p>This model uses a logit link function, logit(p)=log( 1−p/p), to connect the predictors to the probability of the outcome, ensuring that the predicted probabilities are always between 0 and 1</p>
<p><strong>What Happens When You Fit a Normal Linear Model to Binary Data?</strong> Fitting a normal linear model (using lm() in R) to binary data is inappropriate and leads to Nonsensical Predictions: The model can predict probabilities less than 0 or greater than 1</p>
<p>Constant Variance (Homoscedasticity): Linear models assume the variance of the errors is constant. With binary data, the variance depends on the probability itself and is not constant(heteroscedasticity), which violates a core assumption of the model.</p>
<p><strong>How to Interpret Coefficients from a Logistic Regression</strong> The coefficients (Estimate in the R summary) from a logistic regression are on the log-odds scale and are not directly interpretable as changes in probability. To interpret them, you must exponentiate the coefficient (e^β) to get an odds ratio.</p>
<p>For a continuous predictor (e.g., age): If the coefficient for age is β, then e^β is the odds ratio. This means for a one-year increase in age, the odds of the outcome (e.g., having the disease) are multiplied by a factor of e^β.</p>
<p>For a categorical predictor (e.g., SexM): If the coefficient for a male patient is β, then e^β is the odds ratio comparing males to the baseline category (females). The odds of the outcome for a male are e^β times the odds for a female.</p>
</section>
<section id="poisson-part" class="level2">
<h2 class="anchored" data-anchor-id="poisson-part">Poisson part</h2>
<p>Load the InsectSprays dataset and have a look at the help page for it. Note that no add-on package needs to be loaded, this is a R “built-in” dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(InsectSprays)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(InsectSprays)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong> Use an appropriate function to visualise the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(count <span class="sc">~</span> spray, <span class="at">data =</span> InsectSprays,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Type of spray"</span>, <span class="at">ylab =</span> <span class="st">"Insect count"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"InsectSprays data"</span>, <span class="at">varwidth =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"lightgray"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercises_R_binomial_Poisson_files/figure-html/boxplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(InsectSprays, <span class="fu">aes</span>(<span class="at">x =</span> spray, <span class="at">y =</span> count, <span class="at">fill =</span> spray)) <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  <span class="co"># Add a semi-transparent boxplot</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span><span class="fl">0.5</span>) <span class="sc">+</span>   <span class="co"># Add the raw data points with some jitter</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Insect Counts by Spray Type"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Type of Spray"</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Insect Count"</span>)<span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercises_R_binomial_Poisson_files/figure-html/jitter_layer_ggplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(InsectSprays, <span class="fu">aes</span>(<span class="at">x =</span> spray, <span class="at">y =</span> count, <span class="at">fill =</span> spray)) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> <span class="st">"median"</span>, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span> <span class="co"># Add a dot for the median</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Insect Counts by Spray Type"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Type of Spray"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Insect Count"</span>) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercises_R_binomial_Poisson_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The width of the violin at any point on the vertical axis shows how many data points are concentrated at that value.</p>
<p><strong>Question</strong> What do you observe on the graph? Are there differences among groups? Is the variability within each group similar? <strong>answer</strong>: Sprays C, D, and E have very low medians, confirming they are the most effective at reducing insect counts.</p>
<p>Sprays A, B, and F have much higher medians, indicating they were less effective.Most Effective Sprays: C, D, and E are clearly the most effective sprays. They resulted in consistently low insect counts, with most observations clustered near zero.</p>
<p>Least Effective Sprays: A, B, and F were the least effective. They left a much higher number of insects, with counts ranging up to over 20.</p>
<p>Variability: The plot also shows that the results for sprays C, D, and E were less variable (the violins are shorter) than for A, B, and F.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>poisson_model<span class="ot">&lt;-</span><span class="fu">glm</span>(count<span class="sc">~</span> spray, <span class="at">data=</span>InsectSprays, <span class="at">family=</span><span class="st">"poisson"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(poisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = count ~ spray, family = "poisson", data = InsectSprays)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  2.67415    0.07581  35.274  &lt; 2e-16 ***
sprayB       0.05588    0.10574   0.528    0.597    
sprayC      -1.94018    0.21389  -9.071  &lt; 2e-16 ***
sprayD      -1.08152    0.15065  -7.179 7.03e-13 ***
sprayE      -1.42139    0.17192  -8.268  &lt; 2e-16 ***
sprayF       0.13926    0.10367   1.343    0.179    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 409.041  on 71  degrees of freedom
Residual deviance:  98.329  on 66  degrees of freedom
AIC: 376.59

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p><strong>interpretation</strong> Intercept (Spray A): The exponentiated intercept, e^2.667≈14.4, represents the estimated mean insect count for the baseline group, Spray A.</p>
<p>Spray B: The exponentiated coefficient for Spray B is approximately 1.04. This means the mean insect count for Spray B is about 1.04 times that of Spray A (or 4% higher), suggesting it is slightly less effective than Spray A.</p>
<p>Spray C: The exponentiated coefficient for Spray C is approximately 0.14. This means the mean insect count for Spray C is only 0.14 times that of Spray A (an 86% reduction). This indicates that Spray C is much more effective than Spray A.</p>
<p>Spray D: The exponentiated coefficient is 0.34. The mean insect count for Spray D is about one-third of the count for Spray A, making it significantly more effective.</p>
<p><strong>Question</strong> Check whether the model is overdispersed. If this is the case, fit a quasipoisson model and compare the estimated regression coefficients with those of the Poisson model.</p>
<p><strong>answer</strong> A rule of thumb is that if the <strong>residual deviance</strong> is substantially larger than the <strong>degrees of freedom</strong>, the data is overdispersed, meaning there is more variability than the Poisson model assumes.</p>
<p>99&gt;66, so data is overdispersed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the quasipoisson model</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>quasipoisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(count <span class="sc">~</span> spray, <span class="at">data =</span> InsectSprays, <span class="at">family =</span> <span class="st">"quasipoisson"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View the summary</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(quasipoisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = count ~ spray, family = "quasipoisson", data = InsectSprays)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.67415    0.09309  28.728  &lt; 2e-16 ***
sprayB       0.05588    0.12984   0.430    0.668    
sprayC      -1.94018    0.26263  -7.388 3.30e-10 ***
sprayD      -1.08152    0.18499  -5.847 1.70e-07 ***
sprayE      -1.42139    0.21110  -6.733 4.82e-09 ***
sprayF       0.13926    0.12729   1.094    0.278    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for quasipoisson family taken to be 1.507713)

    Null deviance: 409.041  on 71  degrees of freedom
Residual deviance:  98.329  on 66  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the coefficients</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(poisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      sprayB      sprayC      sprayD      sprayE      sprayF 
 2.67414865  0.05588046 -1.94017947 -1.08151786 -1.42138568  0.13926207 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(quasipoisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      sprayB      sprayC      sprayD      sprayE      sprayF 
 2.67414865  0.05588046 -1.94017947 -1.08151786 -1.42138568  0.13926207 </code></pre>
</div>
</div>
<p>the estimated regression coefficients are identical for both the Poisson and quasipoisson models.</p>
<p>What changes are the standard errors of the coefficients, which are larger in the quasipoisson model to account for the extra variability. This leads to more reliable p-values and statistical inference.</p>
<p><strong>Question</strong> Formally test whether there is any evidence that the predictor spray plays a role in the quasipoisson model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, fit the quasipoisson model again</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>quasipoisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(count <span class="sc">~</span> spray, <span class="at">data =</span> InsectSprays, <span class="at">family =</span> <span class="st">"quasipoisson"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># method 1 drop1, Now, use drop1() to test the significance of the 'spray' term</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(quasipoisson_model, <span class="at">test =</span> <span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
count ~ spray
       Df Deviance F value    Pr(&gt;F)    
&lt;none&gt;       98.33                      
spray   5   409.04  41.711 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method 2 anova</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(quasipoisson_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: quasipoisson, link: log

Response: count

Terms added sequentially (first to last)

      Df Deviance Resid. Df Resid. Dev      F    Pr(&gt;F)    
NULL                     71     409.04                     
spray  5   310.71        66      98.33 41.216 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The F-value (41.711): This is the test statistic that measures how much the spray variable improves the model. A large F-value indicates that dropping the spray term significantly worsens the model’s fit.</p>
<p>The p-value (Pr(&gt;F) &lt; 2.2e-16): This value is extremely small, spray is a highly statistically significant predictor</p>
<p><strong>Question</strong> We previously tested whether the predictor spray plays a role. Given that this test was statistically significant, we can dig further and test hypotheses that involve some of the levels of this predictor. Use the glht() function in {multcomp} package to test whether the conventional pesticides “C”, “D” and “E” differ from the organic pesticides “A”, “B” and “F”.</p>
<p>Test also whether the newly developed pesticides “A” and “B” differ from the old conventional pesticide “F”. Use the quasipoisson model to test these hypotheses.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: mvtnorm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: TH.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'TH.data'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:MASS':

    geyser</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>quasipoisson_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(count <span class="sc">~</span> spray, <span class="at">data =</span> InsectSprays, <span class="at">family =</span> <span class="st">"quasipoisson"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the contrast matrix K. Each row is a hypothesis.</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The columns correspond to the spray levels: A, B, C, D, E, F</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Conventional vs Organic"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"New vs Old"</span>              <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>,  <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">2</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the general linear hypothesis test using the defined contrasts</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>hypotheses_test <span class="ot">&lt;-</span> <span class="fu">glht</span>(quasipoisson_model, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">spray =</span> K))</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the summary of the test results</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hypotheses_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: User-defined Contrasts


Fit: glm(formula = count ~ spray, family = "quasipoisson", data = InsectSprays)

Linear Hypotheses:
                             Estimate Std. Error z value Pr(&gt;|z|)    
Conventional vs Organic == 0  -4.6382     0.3823 -12.132   &lt;1e-10 ***
New vs Old == 0               -0.2226     0.2168  -1.027    0.516    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p><img src="explanation%201.png" class="img-fluid" alt="explanation 1"> <img src="explanation%202.png" class="img-fluid" alt="explanation 2"></p>
<hr>
<p><strong>interpretation</strong><br>
Conventional vs.&nbsp;Organic</p>
<p><strong>reject the null hypothesis</strong>. There is strong statistical evidence that the conventional pesticides (C, D, and E) are significantly more effective than the organic pesticides (A, B, and F).</p>
<p><strong>New vs.&nbsp;Old</strong></p>
<p><strong>fail to reject the null hypothesis</strong>. There is no statistical evidence of a difference in effectiveness between the newly developed pesticides (A and B) and the old conventional pesticide (F).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="explanation%203.png" class="img-fluid figure-img"></p>
<figcaption>explanation 3</figcaption>
</figure>
</div>
<p><strong>Questions for ai</strong></p>
<section id="differences-between-count-and-continuous-data" class="level4">
<h4 class="anchored" data-anchor-id="differences-between-count-and-continuous-data"><strong>1 Differences Between Count and Continuous Data</strong></h4>
<p>The primary difference between count and continuous data lies in the values they can take.</p>
<ul>
<li><p><strong>Count Data</strong>: Consists of non-negative integers (0, 1, 2, 3, …). It represents things that can be counted, like the number of items purchased by a customer or the number of children in a family. The values are discrete and have clear gaps between them.</p></li>
<li><p><strong>Continuous Data</strong>: Can take any value within a given range. It represents measurements, like height, weight, or temperature. There are infinite possible values between any two points. For example, a person’s height can be 175 cm, 175.1 cm, or 175.11 cm.</p></li>
</ul>
</section>
<section id="what-model-should-you-fit-to-count-data" class="level4">
<h4 class="anchored" data-anchor-id="what-model-should-you-fit-to-count-data"><strong>2. What Model Should You Fit to Count Data?</strong></h4>
<p>For count data, the standard and most appropriate model is a <strong>Poisson model</strong>. This is a type of Generalized Linear Model (GLM) specifically designed for count outcomes.</p>
<p>The Poisson model is suitable because it assumes the data follows a Poisson distribution and uses a <strong>log link function</strong> to ensure that all predicted counts are non-negative. For data with more variability than the Poisson model assumes (a common issue called overdispersion), a <strong>quasipoisson model</strong> is a better choice.</p>
<p>Overdispersion means that there is more variability (or “scatter”) in your data than what your statistical model predicts. It’s a common issue when modeling count or proportion data.</p>
</section>
<section id="how-to-interpret-coefficients-from-a-poisson-model" class="level4">
<h4 class="anchored" data-anchor-id="how-to-interpret-coefficients-from-a-poisson-model"><strong>4. How to Interpret Coefficients from a Poisson Model</strong></h4>
<p>The coefficients from a Poisson model are on a <strong>logarithmic scale</strong>, so they are not interpreted additively. To interpret them correctly, you must exponentiate the coefficient (eβ) to get a <strong>rate ratio</strong> or <strong>multiplicative factor</strong>.</p>
<ul>
<li><p><strong>For a categorical predictor (e.g., <code>sexM</code>)</strong>: If the coefficient for males is β, then eβ is the rate ratio. For example, if eβ≈1.12, it means males are expected to have, on average, <strong>1.12 times</strong> the count of females (or 12% more).</p></li>
<li><p><strong>For a continuous predictor (e.g., <code>visits</code>)</strong>: If the coefficient for visits is β, then for a one-unit increase in visits, the expected count is multiplied by a factor of eβ.</p></li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>