Dongyuan part of the report analysis, we can work on each different rmd files, and compile in the end together.

Machine Learning 1 Project:
Predicting and Analysis of Student Data with Various ML Models

# Data Source
## Choosing our dataset
Our goal is to deliver a solid report while using the report as a way to enhance our machine learning 1 learning.
With this goal in mind, we started search of appropriate data for our final delivery. We had 3 ideas in mind,
first, **Social Media Fact Sheet** from **PEW Research Center**, 
secondly, medical quality serivce in switzerland from https://opendata.swiss/fr/organization/bundesamt-fur-gesundheit-bag. Third, student data for predicting and anlysis from https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success.

In the end, we have chosen the third option from UC Irvine mahine learning repository. As the data structure and scope aligns with our goal of getting familiarized with machine learning concepts and practices, and produce a solid report as our first atempt in the ML world. The other 2 datasets, though fun to explore around, however, due to structure, diversity and scope, might not suit our goal of learning.